"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";

import { useEffect, useState } from "react";
import { usePathname } from "next/navigation";
import Transition from "@/components/layout/Transition";
import PreLoader from "@/components/layout/PreLoader";
import { ThemeProvider } from "@/components/context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  const [isInitialLoading, setIsInitialLoading] = useState(true);
  const [loading, setLoading] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    // If the preloader is still active, simply return and do nothing.
    // This prevents the transition from running underneath the preloader.
    if (isInitialLoading) return;

    // Trigger the transition animation
    setLoading(true);
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);

    return () => clearTimeout(timer);

    // KEY FIX: Remove 'isInitialLoading' from the dependency array.
    // This ensures the effect only runs when the user navigates (pathname changes),
    // not when the preloader simply turns off.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname]);

  return (
    <html lang="en">
      <head>
        <title>Vinay's Portfolio</title>
        <link rel="icon" href="/vinay.png" />
        <meta name="description" content="Generated by create next app" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          {isInitialLoading ? (
            <PreLoader onLoaded={() => setIsInitialLoading(false)} />
          ) : (
            <>
              {loading && <Transition />}
              <Layout>{children}</Layout>
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
